### ISSUE TITLE
Fix input prompt overlapping with user coordinates when getting user location

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#100]
When the user clicks on 'use my location', the input field will be populated with their current coordinates. Currently, the coordinates overlap with the placeholder text 'enter address or location'. This can be resolved by clicking on the input field which moves the placeholder text away, but is there a way to trigger that programmatically?

Current behavior:
![overlap](https://user-images.githubusercontent.com/515572/26994312-fbad7d3c-4d1b-11e7-8459-311f38137f4c.jpg)

What we want:
![no-overlap](https://user-images.githubusercontent.com/515572/26994322-088417be-4d1c-11e7-8312-4cdd376da4e6.jpg)

**Comment by mfmunic** [comment]
Can it just run the search directly?

**Comment by vinson-ridenour** [comment]
Just did a pull request for this. If we're keeping it, I could only get it to work in Firefox. I couldn't get my coords to populate no matter what I did in Chrome. Hrm.

**Comment by jhuynh85** [comment]
Closed in PR #103
