### ISSUE TITLE
TODO: Click logo to return to initial screen

### ISSUE THREAD

**Issue by vinson-ridenour** [jhuynh85/Project1#19]

**Comment by mfmunic** [comment]
I'll trade you this issue for fixing the css for the new button and modal.

**Comment by mfmunic** [comment]
This has been added.

**Comment by andyhe0x21** [comment]
Hi Joseph

How did you validate the user input? Actually I can add something to
function "getCoorUserInput" to do this. I think the response JSON of the
AJAX in this function also has a field called "valid". I can also add one
more check in this function.

**Comment by jhuynh85** [comment]
Closed in PR #21
