### ISSUE TITLE
TODO: User validation when adding a new place

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#23]
Ensure input string is a valid location when user adds a new venue

**Comment by andyhe0x21** [comment]
If user input "address" does not get a valid response from Google API, what do you want function getCoorUserInput(address)  to return?

**Comment by jhuynh85** [comment]
Probably null

**Comment by andyhe0x21** [comment]
I Added empty string detection and added a condition statement to deal with ZERO_RESULTS response in #28

**Comment by jhuynh85** [comment]
Closed in PR #28
