### ISSUE TITLE
TODO: Pick a site name

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#24]
Are we going with AARF?

**Comment by vinson-ridenour** [comment]
I think it's catchy but I'm definitely not married to it. It was just a placeholder name. I'll try and think of some others before Sat.

**Comment by vinson-ridenour** [comment]
What do we think about any of these for site names?

Ruff It
Ruffing It
Ruff Travel
Travel Ruff
Go Ruff
Paws Aboard
Travel Buddy or Travel Spot (quite punny)
Dog Is My Copilot
...aaaand that's all I got for now.

**Comment by mfmunic** [comment]
Dogpile
Take My Dog, Please!
Barks and Friends
Doggrs
MVP: Please give us an A
Happy Dog - Happy Person

I like Ruff Travel and Dog is My Copilot

**Comment by vinson-ridenour** [comment]
Doggrs - the dating app for dogs. Could be a good project idea...

**Comment by mfmunic** [comment]
I just read an article in SDBJ about top 5 tech name techniques.  Some takeaways:
Misspellings - changing i to y, dropping letters etc
First Names - Alexa, Oscar
Names of Food - Apple

Dogepyle
Spyke
Apple

**Comment by vinson-ridenour** [comment]
Hmm so many possibilities...roverr? We can discuss in person tomorrow to finalize. 

@jhuynh85 did the article say anything about upper/lowercase letters? All lowercase seems to be popular nowadays.

**Comment by mfmunic** [comment]
dogepile!
