### ISSUE TITLE
TODO: Get results from Firebase and display in table

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#25]

**Comment by andyhe0x21** [comment]
basic function implemented as part of #32

**Comment by jhuynh85** [comment]
@mfmunic Do you think you can finish this off? 

I added the `displayVenue` function inside `app.js` which will take an array of venue objects and display them in a table. 

I used your table structure from the meetup table but the yelp results will need a couple additional columns: phone number and an image column to display the thumbnail.

Also, instead of a meetup icon, there should be a different icon depending on the venue type (restaurant, park, hotel)

Let me know if you have any questions

**Comment by mfmunic** [comment]
Restaurants populate in the table

**Comment by mfmunic** [comment]
@vinson-ridenour can you fix styling?

**Comment by jhuynh85** [comment]
Closed in PR #78
