### ISSUE TITLE
TODO: Google Maps API functions

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#3]
**map.js**

**INPUT**
coordinate of current location
coordinates of result location(s)

Something like
        var myLocation = {lat: 32.7157, lng: -117.1611};
        var losangeles = [{lat: 34.0522, lng: -118.2437}, ]{lat: 37.7749, lng: -122.4194}];

**OUTPUT**
Embeddable Google Maps element? (TBD)

**Comment by andyhe0x21** [comment]
Hello Joseph

The only HTML element used by my My function would be a predefined
empty div block. My function returns nothing.

I will send you code in a few days.

**Comment by jhuynh85** [comment]
Hey Andy, can you make another version of your function that takes an address and makes a marker of it on the map?

**Comment by andyhe0x21** [comment]
Closed in PR #11
