### ISSUE TITLE
TODO: Retrieve pet-friendly events from Meetup API

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#30]
**Filename:** meetup.js

**Function:** `meetupSearch()`

**Output:** Searches for pet-related events and returns an array of objects with the following properties: eventName, date, time (military time), location, address, phone (optional?). 

Ex.
```
[{
    eventName: "Doggy date",
    date: "06/05/2017",
    time: "16:00",
    location: "Doyle Community Dog Park",
    address: "8175 Regents Rd, San Diego, CA 92037",
    phone: "123-456-7890"
  },
  {
    eventName:
    date:
    time: 
    location:
    .
    .
    .
  }
]
```

I haven't looked at the Meetups API yet so I'm not even sure all this info is readily available, but this is the ideal format that we like the data to be in. If you have any issues feel free to let us know!

**Comment by mfmunic** [comment]
So far:
event name, location, street address, city, and state. are retrieved.  In the table, the event name opens a link to the meetup page.

**Comment by mfmunic** [comment]
This works, but function needs to be called and tested.
