### ISSUE TITLE
separating address input

### ISSUE THREAD

**Issue by mfmunic** [jhuynh85/Project1#35]
the meetup api only uses zipcode and do we make a distance from user point available to change by user?

**Comment by jhuynh85** [comment]
It only returns the zip? I thought the events have an address associated with them?

And what do you mean 'make a distance from user point available to change by user'?

**Comment by mfmunic** [comment]
For geo-based requests, you may provide a location in one of three ways. By latitude and longitude, by zip, or by country, city, and optionally a state, if the provided country has states.

**Comment by mfmunic** [comment]
Letting the user decide the radius of the search

**Comment by mfmunic** [comment]
Just saw the #26 todo, that answers the second half of the question.

**Comment by jhuynh85** [comment]
Probably do this in increments of 5 miles, from 5 to 20?

**Comment by mfmunic** [comment]
Since we turn the address into a coordinates and search that way, this is no longer an issue.
