### ISSUE TITLE
Pre-calculate longitude and latitude when storing venues into Firebase

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#43]
Call `getCoorUserInput()` on each venue as they are being read from the .json file and store the longitude and latitude as `lng` and `lat` properties for each venue

**Comment by andyhe0x21** [comment]
Finished in #45 

Now firebase looks like this
![image](https://cloud.githubusercontent.com/assets/13608211/26775942/fad655b6-498b-11e7-98d9-4209cc3fae64.png)

Please note that there is one issue with park.json: a park does not an address
![image](https://cloud.githubusercontent.com/assets/13608211/26775998/443ee8e4-498c-11e7-9dd9-5b9d710aac5e.png)
