### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#48]
Format: Powerpoint
Length: 10 minutes

**Comment by mfmunic** [comment]
I think the flow for the presentation:
1) Vinse - Idea for the site, css
2) Marc - UI and Meetup Api
3) Andy - Google Api and calculating coordinates
4) Joseph - Yelp Firebase project manager

**Comment by vinson-ridenour** [comment]
Sounds like a good flow to me. 

Should we keep it to about 1-2 slides each (mainly for talking points & any roadblocks/setbacks we each encountered/overcame)?

Also, when do we want to demo the app?

For closing we can say what features we'd like to add which will make it even more awesome (I can take this last part on or we can individually say what we'd like to improve upon in our respective areas).

**Comment by mfmunic** [comment]
Do we need to do a powerpoint?  Can we just show the website?

I think only one person should talk about missing features, so it doesn't sound like we're all bashing our website with all the stuff that we're missing.  If we all spend 1-2 minutes talking about our portion including obstacle/s that we overcame. That leaves enough time to end with you coming back and talking about extra features.

**Comment by vinson-ridenour** [comment]
I'm ok either way on the powerpoint. If at least one of us would like it we should all use it to be consistent. I'm cool with coming back at the end to talk about enhancements.

We're not taking questions at the end, are we? Haha

**Comment by jhuynh85** [comment]
We'll clarify with Jeff tonight as to what the format of the presentation should be. I'm fine with just doing a demo and no Powerpoint.

**Comment by mfmunic** [comment]
I like the idea of using google slides.  I will work on them.  After last night, we will want to remember not to spend a lot of time each on the slides so that we can demo the site.

**Comment by jhuynh85** [comment]
I think we should get to campus early Saturday morning to practice

**Comment by mfmunic** [comment]
I'm down to get there early.  What time?

**Comment by jhuynh85** [comment]
8, 8:30? Is that too early?

**Comment by mfmunic** [comment]
I was thinking more like 9.  An hour gives us plenty of time to run through a couple of times.

**Comment by andyhe0x21** [comment]
Good job guys!
