### ISSUE TITLE
Highlight marker when hovering on address and vice versa

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#58]
Add this functionality:
1. When the user hovers over a row in the table, the corresponding marker in the map should be highlighted.
2. When the user hovers over a marker in the map, the corresponding row in the table should be highlighted.

Try checking this page for info? 

https://stackoverflow.com/questions/26587533/how-to-highlight-map-marker-upon-selection-of-an-html-element/26588306

**Comment by andyhe0x21** [comment]
released as part of #73
