### ISSUE TITLE
TODO: Input field for user to add a new venue

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#8]
An input field where the user can add a pet-friendly location to the database. There should be a dropdown for them to categorize the location (restaurant, park, etc.)

**Comment by jhuynh85** [comment]
Something like this: 

![fetch_submit](https://cloud.githubusercontent.com/assets/515572/26658711/ccfecfe2-4620-11e7-95c9-ccb3f0c38a70.gif)

**Comment by jhuynh85** [comment]
We might also want to add an address field in addition to the name

**Comment by mfmunic** [comment]
Added modal with form for adding a new venue.  Is there a way to validate an address using the google api?

**Comment by jhuynh85** [comment]
@andyhe829's response from the other issue:

> How did you validate the user input? Actually I can add something to
function "getCoorUserInput" to do this. I think the response JSON of the
AJAX in this function also has a field called "valid". I can also add one
more check in this function.

I think there should be a way to validate user input? We'll take care of it in the back end.

**Comment by jhuynh85** [comment]
Input box added in PR #21. Leaving this issue open until all styling is done for the modal.
