### ISSUE TITLE
Reduce radius scale

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#82]
Right now it seems like we're getting a huge amount of results for our default radius (5 miles). Probably should change the default to 2 miles and then have options for 2 miles, 5 miles, and 10 miles in the dropdown.

**Comment by jhuynh85** [comment]
This is probably because our distance calculator calculates distance from point-to-point and not by length of the travel route between the two points.

**Comment by mfmunic** [comment]
done in pull #86
