### ISSUE TITLE
TODO: Google Maps API - Filter by distance

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#9]
`filterRadius(myLoc, distance, places)`

**INPUT**
myLoc - object with two properties, _lat_ and _long_
distance - number (in meters)
places - array of objects with _lat_ and _long_ properties

**OUTPUT**
Return an array containing all objects in **_places_** that are within **_distance_** meters of **_myLoc_**

**Comment by andyhe0x21** [comment]
A new function will be developed as part of map.js.

**Comment by andyhe0x21** [comment]
#17  merged by Joseph
