### ISSUE TITLE
Add functionality to give user a route between starting location and venue?

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#96]

**Comment by jhuynh85** [comment]
@andyhe829  can you make the following function in `map.js`

`function getRoute(pointA, pointB)`

**INPUT**
`pointA` - Object with two properties: `lat` and `lng`
`pointB` - Object with two properties: `lat` and `lng`

**RESULT**
Display a route on the map from `pointA` to `pointB`

**Comment by andyhe0x21** [comment]
I will start developing this after I go home tonight. But please keep a copy of the project that does not have anything related to this feature because the it is a little too close to tomorrow's presentation and adding new feature at this time is a little risky.

**Comment by jhuynh85** [comment]
Ok, never mind then, I'll just work on this if I have time. It'll probably be too late when you get home.

**Comment by andyhe0x21** [comment]
https://developers.google.com/maps/documentation/javascript/examples/directions-complex

I found this tutorial on creating route on a map.

**Comment by andyhe0x21** [comment]
#109
